
trigger:
  branches:
    include:
      - main  # Trigger the pipeline when the main branch is updated

schedules:
- cron: "0 3 * * *"  # Scheduler to run tests daily at 3 AM (UTC)
  displayName: "Daily Selenium Test Run"
  branches:
    include:
      - main
  always: true

pool:
  vmImage: 'windows-latest'  # Use Windows VM for testing

variables:
  MAVEN_OPTS: "-Xmx1024m"




steps:
- script: |
    echo "Setting up Java 11..."
    sudo apt-get update
    sudo apt-get install -y openjdk-11-jdk
    java -version
  displayName: "Install Java 11"


- task: UseJava@1
  inputs:
    version: '11'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml
    goals: 'clean test'
    options: '-Dwebdriver.gecko.driver=$(System.DefaultWorkingDirectory)/geckodriver.exe'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/surefire-reports/*.xml'
    testRunTitle: 'BDD Selenium Test Results'
